### ISSUE TITLE
Specifying severity levels doesn't disable warnings

### ISSUE THREAD

**Issue by ezrafree** [snyk/vscode-extension#146] opened 2022-02-03 23:35 UTC
As shown in the below screenshot, when unchecking severity levels those issues disappear from the Code Quality section of the Snyk sidebar, but do not disappear from the Problems tab at the bottom.

For me at least (and I suspect others), this is problematic because I use the Problems tab a lot during development.

![Screen Shot 2022-02-03 at 4 25 45 PM](https://user-images.githubusercontent.com/89995868/152446411-5c8d93d4-6104-4650-9cb0-f64621e5f34e.png)

**Comment by michelkaporin** [comment] 2022-02-15 13:09
Closing as duplicate of #138.

**Comment by ezrafree** [comment] 2022-02-15 15:00
Just to clarify, the bug I'm reporting is very similar, but not 100% the same. In my case I still want the warnings, but only for the severity levels that I've specified. Having said that, if your team feels fixing one bug will fix the other, that makes sense too and therefore would make sense to close this one. Thanks!

**Comment by michelkaporin** [comment] 2022-02-15 16:25
@ezrafree you're absolutely correct, that's a different issue. Thank you for raising this. We've put it on our backlog and I'll make sure to ping you once it's out :)

**Comment by michelkaporin** [comment] 2022-04-13 12:59
@ezrafree problems should respect severity filters from settings now ✅

**Comment by michelkaporin** [comment] 2022-04-13 13:00
Fixed in #192.

**Closed by michelkaporin** 2022-04-13 12:59 UTC
Labels: enhancement
